sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

addons:
  postgresql: "9.3"

services:
  - redis

before_script:
  - psql -c "create user logincidadao with password '';" -U postgres
  - psql -c "create database logincidadao with owner logincidadao" -U postgres
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer self-update
  - composer install --prefer-dist
  - chmod -R 777 app/cache app/logs web/uploads
  - echo y | php app/console doctrine:schema:update --force
  - echo y | php app/console doctrine:schema:update --em=logs --force
  - echo y | php app/console lc:database:populate batch/

script:
  # Do NOT enable test coverage here since it takes way too much time
  # We'll use Scrutinizer for that.
  - ./bin/phpunit -c app
