parameters:
    meurs.helper.class: PROCERGS\LoginCidadao\CoreBundle\Helper\MeuRSHelper
    meurs.person_meurs.form.class: PROCERGS\LoginCidadao\CoreBundle\Form\PersonMeuRSType
    meurs.person_meurs.voter_registration.form.class: PROCERGS\LoginCidadao\CoreBundle\Form\PersonMeuRSVoterRegistrationType

    procergs_logincidadao.nfgws.class: PROCERGS\LoginCidadao\CoreBundle\Helper\NfgWsHelper

    lc.person_doc.form.class: PROCERGS\LoginCidadao\CoreBundle\Form\DocFormType

services:
    meurs.entities.person_meurs.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - PROCERGS\LoginCidadao\CoreBundle\Entity\PersonMeuRS

    procergs_logincidadao.nfgws:
        class: %procergs_logincidadao.nfgws.class%
        calls:
            - [setMeuRSHelper, ["@meurs.helper"] ]
            - [setUrl, ["%nfg_ws_url%"]]
            - [setOrganizacao, ["%soe_organization%"]]
            - [setUsuario, ["%soe_username%"]]
            - [setSenha, ["%soe_password%"]]

    meurs.helper:
        class: "%meurs.helper.class%"
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@meurs.entities.person_meurs.repository"

    meurs.person_meurs.form:
        class: "%meurs.person_meurs.form.class%"
        tags:
            - { name: form.type, alias: person_meurs_type }

    meurs.person_meurs.voter_registration.form:
        class: "%meurs.person_meurs.voter_registration.form.class%"
        tags:
            - { name: form.type, alias: person_meurs_voter_registration_type }

    lc.person_doc.form:
        class: "%lc.person_doc.form.class%"
        calls:
            - [setMeuRSHelper, ["@meurs.helper"] ]
        tags:
            - { name: form.type, alias: person_doc_form_type }

    rs.person.serialize.listenner:
        class: PROCERGS\LoginCidadao\CoreBundle\EventListener\PersonSerializeEventListenner
        arguments:
            - "@meurs.helper"
            - "@jms_serializer"
        tags:
            - { name: jms_serializer.event_listener, event: serializer.post_serialize, method: onPostSerialize }

    lc.person_rs.twig.extension:
        class: PROCERGS\LoginCidadao\CoreBundle\Twig\Extension\RsExtension
        arguments:
            - "@meurs.helper"
        tags:
            - { name: twig.extension, alias: login_twig_extension }
