services:
    procergs.lc.procergs_systems.api.client:
        class: GuzzleHttp\Client
        private: true

    procergs.lc.procergs_link.repository:
        myrepository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - PROCERGS\LoginCidadao\AccountingBundle\Entity\ProcergsLink

    procergs.lc.procergs_systems.api:
        class: PROCERGS\LoginCidadao\AccountingBundle\Service\SystemsRegistryService
        arguments:
            - "@procergs.lc.procergs_systems.api.client"
            - "apiUri": "%accounting.procergs_systems.api.url%"
              "organization": "%accounting.procergs_systems.api.organization%"
              "registration_number": "%accounting.procergs_systems.api.registration_number%"
              "password": "%accounting.procergs_systems.api.password%"
        calls:
            - ['setLogger', ["@?logger"]]

    procergs.lc.accounting:
        class: PROCERGS\LoginCidadao\AccountingBundle\Service\AccountingService
        arguments:
            - "@procergs.lc.procergs_systems.api"
            - "@lc.client.repository"
            - "@procergs.lc.procergs_link.repository"
        calls:
            - ['setLogger', ["@?logger"]]
