services:
    procergs_phone_verification.events.subscriber:
        class: PROCERGS\LoginCidadao\PhoneVerificationBundle\Event\PhoneVerificationSubscriber
        arguments:
            - "@sms"
            - "@translator"
            - "@router"
            - "@procergs_phone_verification.circuit_breaker.sms"
        calls:
            - ['setLogger', ["@?logger"]]
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: phone_verification }

    procergs_phone_verification.update_sent_verification.subscriber:
        class: PROCERGS\LoginCidadao\PhoneVerificationBundle\Event\UpdateSentVerificationSubscriber
        arguments:
            - "@sms"
            - "@procergs_phone_verification.circuit_breaker.sms"
        calls:
            - ['setLogger', ["@?logger"]]
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: phone_verification }

    procergs_phone_verification.circuit_breaker.sms:
        class: Eljam\CircuitBreaker\Breaker
        arguments:
            - "phone_verification.sms"
            - max_failure: "%procergs_phone_verification.max_failures%"
              reset_timeout: "%procergs_phone_verification.reset_timeout%"
              allowed_exceptions:
                - 'PROCERGS\Sms\Exception\InvalidCountryException'
            - "@cache"
            - null
            - "@event_dispatcher"
